services:
  - type: worker
    name: bot-passaporte
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/pw-browsers playwright install chromium --with-deps
    startCommand: PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/pw-browsers python Bot.py
    envVars:
      - key: PRENOTA_EMAIL
        sync: false
      - key: PRENOTA_PASSWORD
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
