services:
  - type: worker
    name: bot-passaporte
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install chromium --with-deps
    startCommand: python Bot.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/pw-browsers
      - key: PRENOTA_EMAIL
        sync: false
      - key: PRENOTA_PASSWORD
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
